// Code generated by mockery v1.0.0. DO NOT EDIT.

package core_mocks

import core "github.com/fbiville/headache/internal/pkg/core"
import mock "github.com/stretchr/testify/mock"

// ExecutionTracker is an autogenerated mock type for the ExecutionTracker type
type ExecutionTracker struct {
	mock.Mock
}

// RetrieveVersionedTemplate provides a mock function with given fields: configuration
func (_m *ExecutionTracker) RetrieveVersionedTemplate(configuration *core.Configuration) (*core.VersionedHeaderTemplate, error) {
	ret := _m.Called(configuration)

	var r0 *core.VersionedHeaderTemplate
	if rf, ok := ret.Get(0).(func(*core.Configuration) *core.VersionedHeaderTemplate); ok {
		r0 = rf(configuration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.VersionedHeaderTemplate)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*core.Configuration) error); ok {
		r1 = rf(configuration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TrackExecution provides a mock function with given fields: configurationPath
func (_m *ExecutionTracker) TrackExecution(configurationPath *string) error {
	ret := _m.Called(configurationPath)

	var r0 error
	if rf, ok := ret.Get(0).(func(*string) error); ok {
		r0 = rf(configurationPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
