// Code generated by mockery v1.0.0. DO NOT EDIT.

package fs_mocks

import fs "github.com/fbiville/headache/fs"
import mock "github.com/stretchr/testify/mock"

// ExecutionTracker is an autogenerated mock type for the ExecutionTracker type
type ExecutionTracker struct {
	mock.Mock
}

// GetLastExecutionRevision provides a mock function with given fields:
func (_m *ExecutionTracker) GetLastExecutionRevision() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadLinesAtLastExecutionRevision provides a mock function with given fields: path
func (_m *ExecutionTracker) ReadLinesAtLastExecutionRevision(path string) (fs.HeaderContents, error) {
	ret := _m.Called(path)

	var r0 fs.HeaderContents
	if rf, ok := ret.Get(0).(func(string) fs.HeaderContents); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(fs.HeaderContents)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
