/*
 * Copyright 2018 Florent Biville (@fbiville)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package fs_test

import (
	"fmt"
	. "github.com/fbiville/headache/fs"
	"github.com/fbiville/headache/fs_mocks"
	"github.com/fbiville/headache/vcs_mocks"
	"github.com/golang/mock/gomock"
	. "github.com/onsi/gomega"
	"os"
	"testing"
	"time"
)

func TestLastExecutionRevisionWithPriorTrackingFile(t *testing.T) {
	I := NewGomegaWithT(t)
	controller := gomock.NewController(t)
	defer controller.Finish()
	vcs := new(vcs_mocks.Vcs)
	defer vcs.AssertExpectations(t)
	fileReader := new(fs_mocks.FileReader)
	defer fileReader.AssertExpectations(t)
	fileWriter := new(fs_mocks.FileWriter)
	defer fileWriter.AssertExpectations(t)

	vcs.On("Root").Return("fake-root", nil)
	fileReader.On("Stat", "fake-root/.headache-run").Return(&FakeFileInfo{FileMode: 0777}, nil)
	fileWriter.On("Write", "fake-root/.headache-run", "# Generated by headache | 42 -- commit me!", os.FileMode(0640)).Return(nil)
	vcs.On("LatestRevision", "fake-root/.headache-run").Return("0xdeadbeef", nil)
	tracker := ExecutionVcsTracker{
		Versioning: vcs,
		FileSystem: FileSystem{FileReader: fileReader, FileWriter: fileWriter},
		Clock:      &FixedClock{},
	}

	revision, err := tracker.GetLastExecutionRevision()

	I.Expect(err).To(BeNil())
	I.Expect(revision).To(Equal("0xdeadbeef"))
}

func TestLastExecutionRevisionWithoutTrackingFile(t *testing.T) {
	I := NewGomegaWithT(t)
	controller := gomock.NewController(t)
	defer controller.Finish()
	vcs := new(vcs_mocks.Vcs)
	defer vcs.AssertExpectations(t)
	fileReader := new(fs_mocks.FileReader)
	defer fileReader.AssertExpectations(t)
	fileWriter := new(fs_mocks.FileWriter)
	defer fileWriter.AssertExpectations(t)

	vcs.On("Root").Return("fake-root", nil)
	fileReader.On("Stat", "fake-root/.headache-run").Return(nil, os.ErrNotExist)
	fileWriter.On("Write", "fake-root/.headache-run", "# Generated by headache | 42 -- commit me!", os.FileMode(0640)).Return(nil)
	vcs.On("LatestRevision", "fake-root/.headache-run").Return("0xdeadbeef", nil)
	tracker := ExecutionVcsTracker{
		Versioning: vcs,
		FileSystem: FileSystem{FileReader: fileReader, FileWriter: fileWriter},
		Clock:      &FixedClock{},
	}

	revision, err := tracker.GetLastExecutionRevision()
	I.Expect(err).To(BeNil())
	I.Expect(revision).To(Equal("0xdeadbeef"))
}

func TestLastExecutionPropagatesVersioningRootError(t *testing.T) {
	I := NewGomegaWithT(t)
	controller := gomock.NewController(t)
	defer controller.Finish()
	vcs := new(vcs_mocks.Vcs)
	defer vcs.AssertExpectations(t)
	fileReader := new(fs_mocks.FileReader)
	defer fileReader.AssertExpectations(t)

	rootError := fmt.Errorf("root error")
	vcs.On("Root").Return("", rootError)
	tracker := ExecutionVcsTracker{
		Versioning: vcs,
		FileSystem: FileSystem{FileReader: fileReader},
		Clock:      &FixedClock{},
	}

	_, err := tracker.GetLastExecutionRevision()

	I.Expect(err).To(Equal(rootError))
}

func TestLastExecutionPropagatesFileSystemStatError(t *testing.T) {
	I := NewGomegaWithT(t)
	controller := gomock.NewController(t)
	defer controller.Finish()
	vcs := new(vcs_mocks.Vcs)
	defer vcs.AssertExpectations(t)
	fileReader := new(fs_mocks.FileReader)
	defer fileReader.AssertExpectations(t)

	fileInfoError := fmt.Errorf("fileinfo error")
	vcs.On("Root").Return("fake-root", nil)
	fileReader.On("Stat", "fake-root/.headache-run").Return(nil, fileInfoError)
	tracker := ExecutionVcsTracker{
		Versioning: vcs,
		FileSystem: FileSystem{FileReader: fileReader},
		Clock:      &FixedClock{},
	}

	_, err := tracker.GetLastExecutionRevision()

	I.Expect(err).To(Equal(fileInfoError))
}

func TestLastExecutionPropagatesFileSystemWriteError(t *testing.T) {
	I := NewGomegaWithT(t)
	controller := gomock.NewController(t)
	defer controller.Finish()
	vcs := new(vcs_mocks.Vcs)
	defer vcs.AssertExpectations(t)
	fileReader := new(fs_mocks.FileReader)
	defer fileReader.AssertExpectations(t)
	fileWriter := new(fs_mocks.FileWriter)
	defer fileWriter.AssertExpectations(t)

	fileWriteError := fmt.Errorf("oopsie writie")
	vcs.On("Root").Return("fake-root", nil)
	fileReader.On("Stat", "fake-root/.headache-run").Return(nil, os.ErrNotExist)
	fileWriter.On("Write", "fake-root/.headache-run", "# Generated by headache | 42 -- commit me!", os.FileMode(0640)).Return(fileWriteError)
	tracker := ExecutionVcsTracker{
		Versioning: vcs,
		FileSystem: FileSystem{FileReader: fileReader, FileWriter: fileWriter},
		Clock:      &FixedClock{},
	}

	_, err := tracker.GetLastExecutionRevision()

	I.Expect(err).To(Equal(fileWriteError))
}

func TestLastExecutionPropagatesFileSystemTouchError(t *testing.T) {
	I := NewGomegaWithT(t)
	controller := gomock.NewController(t)
	defer controller.Finish()
	vcs := new(vcs_mocks.Vcs)
	defer vcs.AssertExpectations(t)
	fileReader := new(fs_mocks.FileReader)
	defer fileReader.AssertExpectations(t)
	fileWriter := new(fs_mocks.FileWriter)
	defer fileWriter.AssertExpectations(t)

	writeError := fmt.Errorf("write error")
	vcs.On("Root").Return("fake-root", nil)
	fileReader.On("Stat", "fake-root/.headache-run").Return(&FakeFileInfo{FileMode: 0777}, nil)
	fileWriter.On("Write", "fake-root/.headache-run", "# Generated by headache | 42 -- commit me!", os.FileMode(0640)).Return(writeError)
	tracker := ExecutionVcsTracker{
		Versioning: vcs,
		FileSystem: FileSystem{FileReader: fileReader, FileWriter: fileWriter},
		Clock:      &FixedClock{},
	}

	_, err := tracker.GetLastExecutionRevision()

	I.Expect(err).To(Equal(writeError))
}

func TestLastExecutionPropagatesVersioningLastRevisionError(t *testing.T) {
	I := NewGomegaWithT(t)
	controller := gomock.NewController(t)
	defer controller.Finish()
	vcs := new(vcs_mocks.Vcs)
	defer vcs.AssertExpectations(t)
	fileReader := new(fs_mocks.FileReader)
	defer fileReader.AssertExpectations(t)
	fileWriter := new(fs_mocks.FileWriter)
	defer fileWriter.AssertExpectations(t)

	latestRevisionError := fmt.Errorf("latest revision error")
	vcs.On("Root").Return("fake-root", nil)
	fileReader.On("Stat", "fake-root/.headache-run").Return(&FakeFileInfo{FileMode: 0777}, nil)
	fileWriter.On("Write", "fake-root/.headache-run", "# Generated by headache | 42 -- commit me!", os.FileMode(0640)).Return(nil)
	vcs.On("LatestRevision", "fake-root/.headache-run").Return("", latestRevisionError)
	tracker := ExecutionVcsTracker{
		Versioning: vcs,
		FileSystem: FileSystem{FileReader: fileReader, FileWriter: fileWriter},
		Clock:      &FixedClock{},
	}

	_, err := tracker.GetLastExecutionRevision()

	I.Expect(err).To(Equal(latestRevisionError))
}

type FakeFileInfo struct {
	FileMode os.FileMode
}

func (*FakeFileInfo) Name() string       { panic("not implemented") }
func (*FakeFileInfo) Size() int64        { panic("not implemented") }
func (*FakeFileInfo) ModTime() time.Time { panic("not implemented") }
func (*FakeFileInfo) IsDir() bool        { panic("not implemented") }
func (*FakeFileInfo) Sys() interface{}   { panic("not implemented") }
func (ffi *FakeFileInfo) Mode() os.FileMode {
	return ffi.FileMode
}

type FixedClock struct{}

func (*FixedClock) Now() time.Time {
	return time.Unix(42, 42)
}
