name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: Check mock sync
        run: |
          make gen-mocks
          if [[ $(git status --porcelain) != '' ]]; then
            >&2 echo 'Mocks out of sync'
            exit 42
          fi
      - name: Build & Test
        run: make all